# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Resolve KSP2 / Room compatibility issue ("unexpected jvm signature V")
ksp.useKSP2=false

# Requerido por KSP + Kotlin integrado en AGP 9 (en caso de que se vuelva a usar)
android.disallowKotlinSourceSets=false
